repos:
- repo: https://github.com/hhatto/autopep8
  rev: v2.3.1
  hooks:
  - id: autopep8
    args:
      - --in-place
      - --aggressive
- repo: https://github.com/pycqa/flake8
  rev: 7.1.1
  hooks:
  - id: flake8
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
