name: Upload Python Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:

    name: Build distribution
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/rac_schemas

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
